// app/api/ai/report/pdf/route.ts
import { NextResponse } from "next/server";
import puppeteer from "puppeteer";

export async function POST(request: Request) {
  try {
    const { assembly, report, date } = await request.json();

    const browser = await puppeteer.launch({
      headless: true,
      args: ['--no-sandbox', '--disable-setuid-sandbox']
    });
    
    const page = await browser.newPage();
    
    // Generate HTML for PDF
    const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <title>AI Church Analysis Report - ${assembly}</title>
        <style>
          body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: #333;
            margin: 0;
            padding: 20px;
          }
          .header {
            text-align: center;
            margin-bottom: 40px;
            border-bottom: 3px solid #4f46e5;
            padding-bottom: 20px;
          }
          .header h1 {
            color: #4f46e5;
            margin-bottom: 10px;
          }
          .metadata {
            display: flex;
            justify-content: space-between;
            margin-bottom: 30px;
            padding: 15px;
            background: #f8fafc;
            border-radius: 8px;
          }
          .content {
            margin-top: 30px;
          }
          .section {
            margin-bottom: 25px;
            page-break-inside: avoid;
          }
          .section-title {
            color: #4f46e5;
            border-bottom: 2px solid #e2e8f0;
            padding-bottom: 8px;
            margin-bottom: 15px;
          }
          .recommendations {
            background: #f0f9ff;
            padding: 20px;
            border-radius: 8px;
            border-left: 4px solid #3b82f6;
            margin-top: 20px;
          }
          .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #e2e8f0;
            text-align: center;
            color: #64748b;
            font-size: 12px;
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>AI Church Analysis Report</h1>
          <h2>${assembly} Assembly</h2>
          <p>Lagos, Nigeria • Generated on ${new Date(date).toLocaleDateString()}</p>
        </div>
        
        <div class="metadata">
          <div>
            <strong>Report Type:</strong> AI-Powered Church Analysis<br>
            <strong>Location:</strong> Lagos, Nigeria
          </div>
          <div>
            <strong>Generated:</strong> ${new Date(date).toLocaleString()}<br>
            <strong>Confidentiality:</strong> Internal Use Only
          </div>
        </div>
        
        <div class="content">
          ${report.split('\n\n').map(para => `
            <div class="section">
              <p>${para}</p>
            </div>
          `).join('')}
        </div>
        
        <div class="footer">
          <p>This report was generated by AI based on church data. Recommendations should be reviewed by church leadership.</p>
          <p>© ${new Date().getFullYear()} Church Management System - AI Analytics</p>
        </div>
      </body>
      </html>
    `;

    await page.setContent(htmlContent, { waitUntil: 'networkidle0' });
    
    const pdfBuffer = await page.pdf({
      format: 'A4',
      printBackground: true,
      margin: {
        top: '20mm',
        right: '20mm',
        bottom: '20mm',
        left: '20mm'
      }
    });

    await browser.close();

    // Return PDF
    return new Response(pdfBuffer, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${assembly}-AI-Report-${new Date().toISOString().split('T')[0]}.pdf"`,
      },
    });

  } catch (error: any) {
    console.error("PDF Generation Error:", error);
    return NextResponse.json(
      {
        success: false,
        error: error.message || "Failed to generate PDF",
      },
      { status: 500 }
    );
  }
}